Constify pointers
Without this, an error is generated because going from a const pointer
to non-const pointer is not allowed (const -> const and non-const ->
const is always ok):

.../src/cust_char.cpp:94:42: error: invalid conversion from ‘const uint8_t*’ {aka ‘const unsigned char*’} to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
   94 |         lcd.DefCustChar(CUST_CHAR_aring, Bitmap_aring);
      |                                          ^~~~~~~~~~~~
      |                                          |
      |                                          const uint8_t* {aka const unsigned char*}
In file included from .../src/cust_char.hpp:6,
                 from .../src/cust_char.cpp:3:
.../Arduino/libraries/SmartLCD/SmartLCDI2C.h:93:54: note:   initializing argument 2 of ‘void SmartLCD::DefCustChar(uint8_t, uint8_t*)’
   93 |         void DefCustChar(uint8_t CharIndex, uint8_t *Data);
      |                                             ~~~~~~~~~^~~~

And regardless, using const is good practice in any case.